name: "Keybase Build Notifications"
author: "marvinpinto"
description: "Send GitHub build notifications to your Keybase team or channel"
inputs:
  opensentinel_owner:
    description: 'The "owner" portion of your Opensentinel (generic) Webhook URL (e.g. https://api.opensentinel.com/kb/webhooks?owner=<THIS VALUE>&token=efgh6789)'
    required: true
  opensentinel_token:
    description: 'The "token" portion of your Opensentinel (generic) Webhook URL (e.g. https://api.opensentinel.com/kb/webhooks?owner=abcd1234&token=<THIS VALUE>)'
    required: true
  job_status:
    description: "Actions build status (e.g. success, failure, cancelled)"
    required: true
  job_name:
    description: "Name to use for this job. If not specified, the workflow name is used instead."
    required: false
  on_success:
    description: 'When a build passes, notify you "always" or "never"?'
    required: false
    default: "always"
  on_failure:
    description: 'When a build fails, notify you "always" or "never"?'
    required: false
    default: "always"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "message-square"
  color: "blue"
